#!/bin/sh

set -e

sau_limits_conf="/etc/security/limits.d/10-saunafs.conf"
sau_pam_d="/etc/pam.d/saunafs"

case "${1}" in
	configure)
		if ! getent passwd saunafs > /dev/null 2>&1
		then
			adduser --quiet --system --group --no-create-home --home /var/lib/leil saunafs
		fi
		if [ ! -f $sau_limits_conf ]; then
			echo "saunafs soft nofile 131072" > $sau_limits_conf
			echo "saunafs hard nofile 131072" >> $sau_limits_conf
			chmod 0644 $sau_limits_conf
		fi
		if [ ! -f $sau_pam_d ]; then
			echo "session	required	pam_limits.so" > $sau_pam_d
		fi
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Ensure proper permissions on data dir and run dir.

SAUNAFS_USER="saunafs"
SAUNAFS_GROUP="saunafs"
LEIL_DATA_PATH="/var/lib/leil"

check_dirs() {
	# check that the metadata dir exists
	if [ ! -d "$LEIL_DATA_PATH" ]; then
		mkdir -p "$LEIL_DATA_PATH"
	fi
	chmod 0755 "$LEIL_DATA_PATH"
	chown -R $SAUNAFS_USER:$SAUNAFS_GROUP "$LEIL_DATA_PATH"
}

check_dirs
#DEBHELPER#

exit 0
