#! /bin/sh

# Ensure proper permissions on data dir and run dir.

SAUNAFS_USER="leil"
SAUNAFS_GROUP="leil"
SAUNAFS_DATA_PATH="/var/lib/leil"

check_dirs() {
	# check that the metadata dir exists
	if [ ! -d "$SAUNAFS_DATA_PATH" ]; then
		mkdir -p "$SAUNAFS_DATA_PATH"
	fi
	chmod 0755 "$SAUNAFS_DATA_PATH"
	chown -R $SAUNAFS_USER:$SAUNAFS_GROUP "$SAUNAFS_DATA_PATH"
}

check_dirs
#DEBHELPER#

# vim: ft=sh
